### ISSUE TITLE
input gene models

### ISSUE THREAD

**Issue by sdwien** [rbundschuh/CLEAR#1]
Dear CLEAR team,
I completed my first test run with CLEAR and it worked alright.
For my actual experiments, I usually use Gencode annotations (and some particular versions thereof), and I would not want to mix annotation types, so I wanted to ask how I can generate the reference table you link to for NCBI RefSeq, from a Gencode gtf file? Is it possible to use a 12-column bed file  generated from the gtf file for the `make_dat.py` step in CLEAR, something that looks like this?

```
chr1	67092164	67231852	ENST00000371007.6	0	-	67093004	67127240	0	8	1440,187,70,113,158,92,86,7,	0,3070,4087,23187,33587,35001,38977,139681,
chr1	67092175	67127261	ENST00000371006.5	0	-	67093004	67127240	0	6	1429,187,70,113,158,96,	0,3059,4076,23176,33576,34990,
chr1	67092175	67127261	ENST00000475209.6	0	-	67093579	67127240	0	7	1429,70,145,68,113,158,96,	0,4076,11062,19401,23176,33576,34990,
chr1	67092396	67127261	ENST00000621590.4	0	-	67096311	67127240	0	3	3925,158,96,	0,33355,34769,
chr1	201283451	201332993	ENST00000263946.7	0	+	201283702	201328836	0	15	453,104,395,145,208,178,63,115,156,177,154,187,85,107,2920,	0,10490,29714,33101,34120,35166,36364,36815,38526,39561,40976,41489,42302,45310,46622,
```

Many thanks,
best,
Sophia

EDIT: I downloaded a table for hg38 and Gencode29 from the UCSC Table Browser. It looks like this:

```
#bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
0	ENST00000371007.6	chr1	-	67092164	67231852	67093004	67127240	8	67092164,67095234,67096251,67115351,67125751,67127165,67131141,67231845,	67093604,67095421,67096321,67115464,67125909,67127257,67131227,67231852,	0	C1orf141	cmpl	cmpl	0,2,1,2,0,0,-1,-1,
0	ENST00000371006.5	chr1	-	67092175	67127261	67093004	67127240	6	67092175,67095234,67096251,67115351,67125751,67127165,	67093604,67095421,67096321,67115464,67125909,67127261,	0	C1orf141	cmpl	cmpl	0,2,1,2,0,0,
0	ENST00000475209.6	chr1	-	67092175	67127261	67093579	67127240	7	67092175,67096251,67103237,67111576,67115351,67125751,67127165,	67093604,67096321,67103382,67111644,67115464,67125909,67127261,	0	C1orf141	cmpl	cmpl	2,1,0,1,2,0,0,
0	ENST00000621590.4	chr1	-	67092396	67127261	67096311	67127240	3	67092396,67125751,67127165,	67096321,67125909,67127261,	0	C1orf141	cmpl	cmpl	2,0,0,
0	ENST00000263946.7	chr1	+	201283451	201332993	201283702	201328836	15	201283451,201293941,201313165,201316552,201317571,201318617,201319815,201320266,201321977,201323012,201324427,201324940,201325753,201328761,201330073,	201283904,201294045,201313560,201316697,201317779,201318795,201319878,201320381,201322133,201323189,201324581,201325127,201325838,201328868,201332993,	0	PKP1	cmpl	cmpl	0,1,0,2,0,1,2,2,0,0,0,1,2,0,-1,
```

However, it does not work with `make_dat.py` which says:

```
Traceback (most recent call last):
  File "/project/Downloads/CLEAR-master/make_dat.py", line 100, in <module>
    results = sorted( test_gene() )[::-1]
  File "/project/Downloads/CLEAR-master/make_dat.py", line 93, in test_gene
    results.append( ( float( total ) / float( model[5] ), mu, model[5], model[1], model[3] ) )       
ZeroDivisionError: float division by zero
```
I then removed the header line (# ... ).
Now it seems to work, so this may well be the answer to my question.
Still, your suggestions and opinions are most welcome.
Best,
Sophia

**Comment by rbundschuh** [comment]
Dear Sophia,

It looks like you have already figured it out. Our suggestion would have been to use the gtftoGenePred tool from UCSC (see [http://genomewiki.ucsc.edu/index.php/Genes_in_gtf_or_gff_format](http://genomewiki.ucsc.edu/index.php/Genes_in_gtf_or_gff_format)) to convert the Gencode gtf to the GenePred format CLEAR uses.

   Yours
             Ralf
